# Generated by Django 3.2.12 on 2022-04-08 09:22

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, verbose_name='Enter Category Name')),
                ('category_photo', models.FileField(help_text='Only PNG, JPG, JPEG format supported', upload_to='Category_Image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Home Background hero image')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_category', models.CharField(choices=[('1', 'lead'), ('2', 'current'), ('3', 'former')], max_length=250, verbose_name='Select Team Category')),
                ('name', models.CharField(max_length=250, verbose_name="Enter Member's Name")),
                ('designation', models.CharField(max_length=250, verbose_name='Member Designation')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name="Member's Email")),
                ('facebook_link', models.CharField(blank=True, help_text='You must input "http://" before insert your link', max_length=250, null=True, verbose_name="Enter Member's facebook link")),
                ('whatsapp_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Enter Whatsapp number')),
                ('instagram_link', models.CharField(blank=True, help_text='You must input "http://" before insert your link', max_length=250, null=True, verbose_name='Enter instagram link')),
                ('image', models.FileField(help_text='Only PNG, JPG, JPEG format supported', upload_to='Team_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Team member image')),
            ],
        ),
        migrations.CreateModel(
            name='SubPackagesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=250, verbose_name='Enter Category Name')),
                ('sub_category_photo', models.FileField(help_text='Only PNG, JPG, JPEG format supported', upload_to='Sub_Category_Image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Sub Category Image')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProminenceApp.packagescategory', verbose_name='Select Main Category')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=250, verbose_name='Enter package name')),
                ('package_price', models.IntegerField(verbose_name='Package Price')),
                ('package_details', ckeditor.fields.RichTextField(verbose_name='Package Details')),
                ('package_photo', models.FileField(help_text='Only PNG, JPG, JPEG format supported', upload_to='Package_Image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Package Image')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProminenceApp.packagescategory', verbose_name='Select Packages Category')),
                ('sub_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='main_category', chained_model_field='main_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='ProminenceApp.subpackagescategory', verbose_name='Select Sub-Packages Category')),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=300, verbose_name='Main Title')),
                ('advertise_title', models.CharField(max_length=300, verbose_name='Advertisement Title')),
                ('terms', ckeditor.fields.RichTextField(verbose_name='Enter terms and conditions')),
                ('policy', ckeditor.fields.RichTextField(verbose_name='Enter policy')),
                ('hero_image_field', models.FileField(help_text='Only PNG, JPG, JPEG format supported', upload_to='services_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Home Background hero image')),
                ('home_video_link', models.CharField(help_text='Add "http://" before your link if not inserted', max_length=250, verbose_name='Enter home video link')),
                ('phone', models.CharField(max_length=20, verbose_name='Company official Mobile/ Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Company official email')),
                ('address', models.CharField(max_length=300, verbose_name='Full Address ')),
                ('facebook_link', models.CharField(help_text="remove 'http://' before your web address, Example: example.com", max_length=300, verbose_name='Facebook Link ')),
                ('whatsapp_link', models.CharField(max_length=300, verbose_name='Whatsapp Link/Mobile number')),
                ('instagram_link', models.CharField(help_text="remove 'http://' before your web address, Example: example.com", max_length=300, verbose_name='Instagram Link')),
                ('linkedin_link', models.CharField(help_text="remove 'http://' before your web address, Example: example.com", max_length=300, verbose_name='Linkedin Link')),
                ('skype_link', models.CharField(help_text="remove 'http://' before your web address, Example: example.com", max_length=300, verbose_name='Skype Link')),
                ('mode', models.CharField(choices=[('1', 'production'), ('2', 'development')], max_length=100, verbose_name='Select Mode')),
                ('last_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('photo', models.FileField(help_text='Only PNG, JPG, JPEG format supported', upload_to='Gallery_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Gallery Image')),
                ('gallery_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ProminenceApp.packagescategory', verbose_name='Select Gallery Category')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_about', models.TextField(help_text='Not more than 300 character', max_length=300, verbose_name='Site Short About')),
                ('long_about', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Site Long About')),
                ('happy_clients', models.IntegerField(blank=True, null=True, verbose_name='Enter Happy clients Count')),
                ('years_of_experience', models.IntegerField(blank=True, null=True, verbose_name='Enter the company work of experiences')),
                ('last_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
