# Generated by Django 3.2.12 on 2022-04-14 20:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ProminenceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='long_about',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Site Long About'),
        ),
        migrations.AlterField(
            model_name='general',
            name='policy',
            field=tinymce.models.HTMLField(verbose_name='Enter policy'),
        ),
        migrations.AlterField(
            model_name='general',
            name='terms',
            field=tinymce.models.HTMLField(verbose_name='Enter terms and conditions'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_details',
            field=tinymce.models.HTMLField(),
        ),
    ]
