# Generated by Django 3.2.10 on 2022-04-01 13:34

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ProminenceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='category',
        ),
        migrations.AddField(
            model_name='packages',
            name='main_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProminenceApp.packagescategory', verbose_name='Select Packages Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='package_details',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Package Details'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='package_name',
            field=models.CharField(default=1, max_length=250, verbose_name='Enter package name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='package_photo',
            field=models.FileField(default=1, help_text='Only PNG, JPG, JPEG format supported', upload_to='Package_Image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Package Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='package_price',
            field=models.IntegerField(default=1, verbose_name='Package Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_category',
            field=models.CharField(choices=[('1', 'lead'), ('2', 'current'), ('3', 'former')], default=1, max_length=250, verbose_name='Select Team Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packages',
            name='sub_category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='main_category', chained_model_field='main_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='ProminenceApp.subpackagescategory', verbose_name='Select Sub-Packages Category'),
        ),
    ]
