# Generated by Django 3.2.12 on 2022-04-08 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProminenceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='about_body_image',
            field=models.FileField(default=1, help_text='Only PNG, JPG, JPEG format supported', upload_to='About image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='About section body image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='general',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='facebook_link',
            field=models.CharField(help_text="Add 'http:// or https://' before your web address if not inserted, Example:(http://example.com)", max_length=300, verbose_name='Facebook Link '),
        ),
        migrations.AlterField(
            model_name='general',
            name='home_video_link',
            field=models.CharField(help_text="Add 'http:// or https://' before your web address if not inserted, Example:(http://example.com)", max_length=250, verbose_name='Enter youtube link for home video'),
        ),
        migrations.AlterField(
            model_name='general',
            name='instagram_link',
            field=models.CharField(help_text="Add 'http:// or https://' before your web address if not inserted, Example:(http://example.com)", max_length=300, verbose_name='Instagram Link'),
        ),
        migrations.AlterField(
            model_name='general',
            name='linkedin_link',
            field=models.CharField(help_text="Add 'http:// or https://' before your web address if not inserted, Example:(http://example.com)", max_length=300, verbose_name='Linkedin Link'),
        ),
        migrations.AlterField(
            model_name='general',
            name='skype_link',
            field=models.CharField(help_text="Add 'http:// or https://' before your web address if not inserted, Example:(http://example.com)", max_length=300, verbose_name='Skype Link'),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.CharField(blank=True, help_text="Add 'http:// or https://' before your web address if not inserted, Example:(http://example.com)", max_length=250, null=True, verbose_name="Enter Member's facebook link"),
        ),
        migrations.AlterField(
            model_name='team',
            name='instagram_link',
            field=models.CharField(blank=True, help_text="Add 'http:// or https://' before your web address if not inserted, Example:(http://example.com)", max_length=250, null=True, verbose_name='Enter instagram link'),
        ),
    ]
